---
apiVersion: inv.sdcio.dev/v1alpha1
kind: DiscoveryRule
metadata:
  name: lei1-leaf-srl-nokia
  namespace: default
spec:
  period: 1m
  concurrentScans: 2
  defaultSchema:
    provider: srl.nokia.sdcio.dev
    version: 24.10.1
  addresses:
    - address: clab-evpn-leaf1
      hostName: clab-evpn-leaf1
    - address: clab-evpn-leaf2
      hostName: clab-evpn-leaf2
  discoveryProfile:
    credentials: srl.nokia.sdcio.dev
    connectionProfiles:
      - srl-nokia-gnmi
  targetConnectionProfiles:
    - credentials: srl.nokia.sdcio.dev
      connectionProfile: srl-nokia-gnmi
      syncProfile: gnmi-get
  targetTemplate:
    labels:
      sdcio.dev/vendor: nokia
      sdcio.dev/nos: srl
      sdcio.dev/region: eu
      sdcio.dev/site: lei1
      sdcio.dev/role: leaf
