---
apiVersion: inv.sdcio.dev/v1alpha1
kind: DiscoveryRule
metadata:
  name: lei1-leaf-eos-arista
  namespace: default
spec:
  period: 1m
  concurrentScans: 2
  defaultSchema:
    provider: eos.arista.sdcio.dev
    version: 4.33.0F
  addresses:
    - address: clab-evpn-leaf3
      hostName: clab-evpn-leaf3
    - address: clab-evpn-leaf4
      hostName: clab-evpn-leaf4
  discoveryProfile:
    credentials: eos.arista.sdcio.dev
    connectionProfiles:
      - eos-arista-gnmi
  targetConnectionProfiles:
    - credentials: eos.arista.sdcio.dev
      connectionProfile: eos-arista-gnmi
      syncProfile: gnmi-get
  targetTemplate:
    labels:
      sdcio.dev/vendor: arista
      sdcio.dev/nos: eos
      sdcio.dev/region: eu
      sdcio.dev/dc: lei1
      sdcio.dev/role: leaf
